package models;

public enum ErrorCodes
{
	DUPLICATE_ACCOUNT,
	DUPLICATE_USER,
	MULTIPLE_ACCOUNTS_WITH_SAME_EMAIL,
	OAUTH_EXCEPTION,
	ACCOUNT_NOT_FOUND,
	UNSUPPORTED_PROVIDER,
	AUTHENTICATION_FAILED,
	INVALID_REQUEST,
	NO_SUCH_USER,
	SERVER_EXCEPTION,
	MAX_ACCOUNT_LIMIT_REACHED
}